### ISSUE TITLE
The game still pops up with an error screen when I set "Do not load with no scripts"=false

### ISSUE THREAD

**Issue by ghost** [Srdjan-V/TweakedPetroleum#3]
I've used the initial startup script, and I have some issues in my other script content that don't handle well and pop up warnings but have no effect on the game, however Tweaked Petroleum still pops up with the error screen, so I set "Do not load with no scripts" to false and ran into this problem.

**Comment by Srdjan-V** [comment]
This will be reworked in the next version. It will be released today
