### ISSUE TITLE
No error when reserviour registered with non-existent fluid

### ISSUE THREAD

**Issue by Krutoy242** [Srdjan-V/TweakedPetroleum#8]
I registered reserviour, but made a mistake, and there is no such liquid as `helium3`. TweakedPetroleum shows no error about it.

```less
registerReservoir("Helium 3 Reservoir (Luna)", <liquid:helium3>, 2000000000, maxInt, 15, 40, 30, I, [], [100], [], []);
```

**Comment by Srdjan-V** [comment]
This seems to be a weird edge case. In the example you provided helium3 is a valid fluid in the registry. If it were not, an exception would have been thrown

I will be implementing a cleaner exception message
